-- Multi-tenant schema baseline
-- Ajuste o valor de v_owner para o tenant padrão (ex.: 'OWNER_PADRAO' ou UUID).
-- Execute em ambiente único (run-once). Em produção, exporte um valor real de owner.

DO $$
DECLARE
  v_owner text := 'CHANGE_ME_OWNER_ID';
BEGIN
  IF v_owner = 'CHANGE_ME_OWNER_ID' THEN
    RAISE EXCEPTION 'Defina v_owner para migrar os dados existentes';
  END IF;

  -- contacts: add owner_id and backfill
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contacts' AND column_name = 'owner_id') THEN
    ALTER TABLE contacts ADD COLUMN owner_id text NOT NULL DEFAULT v_owner;
    UPDATE contacts SET owner_id = v_owner WHERE owner_id = v_owner;
    ALTER TABLE contacts ALTER COLUMN owner_id DROP DEFAULT;
    CREATE INDEX IF NOT EXISTS idx_contacts_owner_id ON contacts (owner_id);
    CREATE UNIQUE INDEX IF NOT EXISTS idx_contacts_owner_phone ON contacts (owner_id, phone);
  END IF;

  -- messages: add owner_id and backfill from contact
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'messages' AND column_name = 'owner_id') THEN
    ALTER TABLE messages ADD COLUMN owner_id text;
    UPDATE messages m SET owner_id = c.owner_id FROM contacts c WHERE m.contact_id = c.id;
    UPDATE messages SET owner_id = v_owner WHERE owner_id IS NULL;
    ALTER TABLE messages ALTER COLUMN owner_id SET NOT NULL;
    CREATE INDEX IF NOT EXISTS idx_messages_owner_id ON messages (owner_id);
  END IF;

  -- campaigns: add owner_id
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'campaigns' AND column_name = 'owner_id') THEN
    ALTER TABLE campaigns ADD COLUMN owner_id text NOT NULL DEFAULT v_owner;
    UPDATE campaigns SET owner_id = v_owner WHERE owner_id = v_owner;
    ALTER TABLE campaigns ALTER COLUMN owner_id DROP DEFAULT;
    CREATE INDEX IF NOT EXISTS idx_campaigns_owner_id ON campaigns (owner_id);
  END IF;

  -- campaign_targets: add owner_id and backfill from campaign
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'campaign_targets' AND column_name = 'owner_id') THEN
    ALTER TABLE campaign_targets ADD COLUMN owner_id text;
    UPDATE campaign_targets ct SET owner_id = c.owner_id FROM campaigns c WHERE ct.campaign_id = c.id;
    UPDATE campaign_targets SET owner_id = v_owner WHERE owner_id IS NULL;
    ALTER TABLE campaign_targets ALTER COLUMN owner_id SET NOT NULL;
    CREATE INDEX IF NOT EXISTS idx_campaign_targets_owner_id ON campaign_targets (owner_id);
  END IF;

  -- memberships table (user <-> owner)
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'memberships') THEN
    CREATE TABLE memberships (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
      owner_id text NOT NULL,
      role text NOT NULL DEFAULT 'member',
      created_at timestamptz NOT NULL DEFAULT now(),
      UNIQUE (user_id, owner_id)
    );
    CREATE INDEX IF NOT EXISTS idx_memberships_owner_id ON memberships (owner_id);
  END IF;
END $$;
